apiVersion: apps/v1
kind: Deployment
metadata:
  name: acrdemo-localdocker-deployment
  labels:
    app: acrdemo-localdocker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acrdemo-localdocker
  template:
    metadata:
      labels:
        app: acrdemo-localdocker
    spec:
      containers:
        - name: acrdemo-localdocker
          image: acrforaksdemo1.azurecr.io/custom2aksnginxapp1:22
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: acrdemo-localdocker-service
  labels:
    app: acrdemo-localdocker
spec:
  type: LoadBalancer
  selector:
    app: acrdemo-localdocker
  ports:
    - port: 80
      targetPort: 80
   